[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "res_sys"
version = "0.0.1"
description = "Rec sys project for HSE"
authors = [
  { name = "Sergey" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.13.0"


[tool.ruff]
line-length = 99
src = ["res_sys"]
include = ["pyproject.toml", "res_sys/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["res_sys"]
force-sort-within-sections = true

